### ISSUE TITLE
implement pretty mode?

### ISSUE THREAD

**Issue by andreacfromtheapp** [hron/zed-org#1]
hi,

would it be possibe to implement pretty? https://docs.doomemacs.org/v21.12/modules/lang/org/#/description/module-flags/pretty

thanks for this exteansion!

**Comment by hron** [comment]
I don't think that this is possible with tree sitter queries. Currently, zed extensions are limited to the tree sitter queries plus an ability to define some commands, so from my point of view this is not possible, but I'm happy to be wrong, so PRs are welcome %)
